name: Build Android

on:
  push:
    branches: [main, master]
    paths:
      - ".github/workflows/android.yml"
      - ".github/workflows/build-common.yml"
      - "scripts/android/**"
      - "scripts/common/**"
      - "patches/android/**"
      - "wraps/**"
  pull_request:
    branches: [main, master]
    paths:
      - ".github/workflows/android.yml"
      - ".github/workflows/build-common.yml"
      - "scripts/android/**"
      - "scripts/common/**"
      - "patches/android/**"
      - "wraps/**"
  workflow_dispatch:

jobs:
  build-x86_64:
    permissions:
      contents: write
    uses: ./.github/workflows/build-common.yml
    with:
      platform: android
      arch: x86_64
      runner_os: ubuntu-latest
      library_type: both
      artifact_name: android-x86_64
      build_name: Android x86_64

  build-aarch64:
    permissions:
      contents: write
    uses: ./.github/workflows/build-common.yml
    with:
      platform: android
      arch: aarch64
      runner_os: ubuntu-latest
      library_type: both
      artifact_name: android-aarch64
      build_name: Android aarch64

  build-armv7a:
    permissions:
      contents: write
    uses: ./.github/workflows/build-common.yml
    with:
      platform: android
      arch: armv7a
      runner_os: ubuntu-latest
      library_type: both
      artifact_name: android-armv7a
      build_name: Android armeabi-v7a
