name: Build Windows

on:
  push:
    branches: [main, master]
    paths:
      - ".github/workflows/windows.yml"
      - ".github/workflows/build-common.yml"
      - "scripts/windows/**"
      - "scripts/common/**"
      - "patches/windows/**"
      - "wraps/**"
  pull_request:
    branches: [main, master]
    paths:
      - ".github/workflows/windows.yml"
      - ".github/workflows/build-common.yml"
      - "scripts/windows/**"
      - "scripts/common/**"
      - "patches/windows/**"
      - "wraps/**"
  workflow_dispatch:

jobs:
  build-x86_64:
    permissions:
      contents: write
    uses: ./.github/workflows/build-common.yml
    with:
      platform: windows
      arch: x86_64
      runner_os: windows-latest
      library_type: shared
      artifact_name: windows-x86_64
      build_name: Windows x86_64
